'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.6400
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Checker

    Partial Public Class ActionMenu

        '''<summary>
        '''btnMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMessage As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnReport As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnProblem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnProblem As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnTrailerCollection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnTrailerCollection As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnMovieTrailer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMovieTrailer As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnExit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnExit As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
