'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8669
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Checker

    Partial Public Class Login

        '''<summary>
        '''txtUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUser As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPwd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPwd As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnTest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnTest As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnLogin1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLogin1 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
