'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.6400
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Checker

    Partial Public Class RemainMovieList

        '''<summary>
        '''lblOwnerRevenue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOwnerRevenue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdOwnerRevenue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdOwnerRevenue As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblOwnerFreeTicket control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOwnerFreeTicket As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdOwnerFreeTicket control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdOwnerFreeTicket As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblOwnerTicketType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOwnerTicketType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdOwnerTicketType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdOwnerTicketType As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblCompetitor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCompetitor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdCompetitor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdCompetitor As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''btnBackToMovieList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBackToMovieList As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
