'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.6400
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Checker

    Partial Public Class SendRevenue

        '''<summary>
        '''lblRevenueDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRevenueDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlSummayOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSummayOwner As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''grdOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdOwner As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblSumScreenFilm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSumScreenFilm As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdOwnerScreenFilm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdOwnerScreenFilm As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblSumOwnerAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSumOwnerAll As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdOwnerAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdOwnerAll As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''pnlSummayComp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSummayComp As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''grdCompetitor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdCompetitor As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblSumCompRevenue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSumCompRevenue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSumCompViewer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSumCompViewer As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSumCompScreen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSumCompScreen As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSumCompSession control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSumCompSession As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnDeleteHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDeleteHeader As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAction As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlOwner As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlScreen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlScreen As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlHour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlHour As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMinute As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlCompRevenueType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCompRevenueType As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlCompRevenueType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCompRevenueType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDetail As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlFilmTypeSound control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFilmTypeSound As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlDetailCompetitor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDetailCompetitor As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtCountScreen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCountScreen As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCountSession control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCountSession As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtRevenue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRevenue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtViewer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtViewer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlCompetitorPreData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCompetitorPreData As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtAllScreen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAllScreen As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAllSession control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAllSession As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAllRevenue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAllRevenue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAllViewer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAllViewer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnCancelEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancelEdit As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblErrorDuplicate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorDuplicate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorRevenue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorRevenue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorHaveDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorHaveDetail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnSend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSend As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
