'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5466
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Checker

    Partial Public Class SendTicketType

        '''<summary>
        '''lblRevenueDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRevenueDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblNotFoundAnyTicketByMovie control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotFoundAnyTicketByMovie As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdOwner As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''pnlRevenue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRevenue As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''grdTicketType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdTicketType As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblCountTicketType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCountTicketType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorCountRevernue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorCountRevernue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAction As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlTicketTypeByMovie control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlTicketTypeByMovie As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtQuantity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtQuantity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnUpdateDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateDetail As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblError0 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError0 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnBackToSendRevenue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBackToSendRevenue As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''hdfPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfPrice As Global.System.Web.UI.WebControls.HiddenField
    End Class
End Namespace
