'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.6400
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Checker

    Partial Public Class Trailer

        '''<summary>
        '''ddlScreen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlScreen As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''MovieFinder1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MovieFinder1 As Global.SDT.UserControls.MovieFinder

        '''<summary>
        '''MovieFinder2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MovieFinder2 As Global.SDT.UserControls.MovieFinder

        '''<summary>
        '''MovieFinder3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MovieFinder3 As Global.SDT.UserControls.MovieFinder

        '''<summary>
        '''MovieFinder4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MovieFinder4 As Global.SDT.UserControls.MovieFinder

        '''<summary>
        '''TrailerCollectionFinder1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TrailerCollectionFinder1 As Global.SDT.UserControls.TrailerCollectionFinder

        '''<summary>
        '''lblErrorDataExist control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorDataExist As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorNotSelectAnyMovie control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorNotSelectAnyMovie As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorSelectDuplicate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorSelectDuplicate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorCollection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorCollection As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnSaveDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveDetail As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnMainMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnMainMenu As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdResult As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''hdfTrailerNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfTrailerNo As Global.System.Web.UI.WebControls.HiddenField
    End Class
End Namespace
