'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.6400
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Checker

    Partial Public Class TrailerCollectionInsert

        '''<summary>
        '''txtCollectionName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCollectionName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblRequire control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRequire As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TrailerCollectionFinder1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TrailerCollectionFinder1 As Global.SDT.UserControls.TrailerCollectionFinder

        '''<summary>
        '''lblErrorCompleteTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorCompleteTextBox As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorDataExist control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorDataExist As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnInsertMore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnInsertMore As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnBackToTrailerCollection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBackToTrailerCollection As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''TrailerFinder1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TrailerFinder1 As Global.SDT.UserControls.TrailerFinder

        '''<summary>
        '''txtSeqNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSeqNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblErrorNotFoundMovie control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorNotFoundMovie As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorMovieExist control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorMovieExist As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorInvalidSeq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorInvalidSeq As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorSeqExist control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorSeqExist As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorInvalidSeqNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorInvalidSeqNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorAll As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnSaveDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveDetail As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancelSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancelSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdResult As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''hdfCollectionNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfCollectionNo As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdfAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfAction As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdfSelectedSeqNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfSelectedSeqNo As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdfSelectedMovieId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfSelectedMovieId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''DivInsertMovie control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DivInsertMovie As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblConfirmRetreat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblConfirmRetreat As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnInsert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnInsert As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancelInsert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancelInsert As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
