'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.6400
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class frmRptCompMarketSareByCircuit

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btnExport0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExport0 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel0 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbHD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHD As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''TableHeaderRow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow1 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableHeaderCell1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderRow2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow2 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableHeaderCell2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderRow3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow3 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableHeaderCell3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''tbBKK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbBKK As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''TableHeaderRow13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow13 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableHeaderCell29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell29 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderRow14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow14 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableHeaderCell30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell30 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell31 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell43 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell44 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell45 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell46 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderRow15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow15 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableHeaderCell47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell47 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell48 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell49 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell50 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableFooterRow4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableFooterRow4 As Global.System.Web.UI.WebControls.TableFooterRow

    '''<summary>
    '''TableCell27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell27 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell28 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell29 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell30 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell31 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell32 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell33 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''tbCM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCM As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''TableHeaderRow16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow16 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableHeaderCell32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell32 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderRow17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow17 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableHeaderCell33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell33 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell34 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell35 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell36 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell37 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell38 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderRow18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow18 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableHeaderCell39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell39 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell40 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell41 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell42 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableFooterRow3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableFooterRow3 As Global.System.Web.UI.WebControls.TableFooterRow

    '''<summary>
    '''TableCell39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell39 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell40 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell41 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell42 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell43 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell44 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell45 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''tbCITY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCITY As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''TableHeaderRow10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow10 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableHeaderCell18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell18 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderRow11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow11 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableHeaderCell19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell19 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell20 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell21 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell22 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell23 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell24 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderRow12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderRow12 As Global.System.Web.UI.WebControls.TableHeaderRow

    '''<summary>
    '''TableHeaderCell25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell25 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell26 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell27 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableHeaderCell28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableHeaderCell28 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TableFooterRow2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableFooterRow2 As Global.System.Web.UI.WebControls.TableFooterRow

    '''<summary>
    '''TableCell1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell1 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell26 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell34 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell35 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell36 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell37 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''TableCell38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell38 As Global.System.Web.UI.WebControls.TableCell
End Class
