'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5466
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class frmRptBoxOfficeAndLateShow3

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btnExport0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExport0 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel0 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divExport As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divExportTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divExportTemplate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbHeaderTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbHeaderTemplate As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tbUserTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUserTemplate As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tbCheckerWageTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCheckerWageTemplate As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tbLateShowTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLateShowTemplate As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tbSummaryTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSummaryTemplate As Global.System.Web.UI.WebControls.Table
End Class
