'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.6400
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Form

    Partial Public Class SendRevenue

        '''<summary>
        '''hdfRevenueDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfRevenueDate As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdfTheaterId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfTheaterId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdfMovieId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfMovieId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hdfUserId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdfUserId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''pnlOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlOwner As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlScreen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlScreen As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlHour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlHour As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlMinute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMinute As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDetail As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlFilmTypeSound control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFilmTypeSound As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtRevenue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRevenue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtViewer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtViewer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlDetailCompetitor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDetailCompetitor As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtCountScreen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCountScreen As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCountSession control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCountSession As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlCompetitorPreData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCompetitorPreData As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtAllRevenue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAllRevenue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAllViewer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAllViewer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAllScreen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAllScreen As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAllSession control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAllSession As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblErrorDuplicate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorDuplicate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorRevenue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorRevenue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnSend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSend As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnRemove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnRemove As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
