'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Revenue
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SDTCommon.Revenue", GetType(Revenue).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT
        '''	rv.movies_id AS movie_id
        '''	, SUM(rv.revenue_amount) AS sum_revenue
        '''	, CASE WHEN MAX(rv.status_id) &lt; 3 THEN 1 ELSE 0 END AS is_complete
        '''FROM tblRevenue AS rv
        '''INNER JOIN tblMovie AS m
        '''ON m.movie_id = rv.movies_id
        '''	AND m.movietype_id = 1
        '''WHERE rv.theater_id = @theater_id
        '''	AND rv.revenue_date = @revenue_date
        '''GROUP BY rv.movies_id
        '''
        '''UNION
        '''
        '''SELECT
        '''	rch.movie_id
        '''	, SUM(rch.all_amount) AS sum_revenue
        '''	, CASE WHEN MAX(rch.status_id) &lt; 3 THEN 1 ELSE 0 END AS is_complete
        '''FROM tblRevenueCompHead [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SelectDailyRevenue() As String
            Get
                Return ResourceManager.GetString("SelectDailyRevenue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DECLARE @name_list AS NVARCHAR(MAX);
        '''DECLARE @sql AS NVARCHAR(MAX);
        '''SET @name_list = &apos;&apos;;
        '''	
        '''IF @screen_id IS NOT NULL AND @theater_id IS NOT NULL
        '''BEGIN
        '''	SELECT @name_list = @name_list + &apos;,[&apos; + ticket_cap_name + &apos;]&apos; 
        '''	FROM
        '''	(
        '''		SELECT DISTINCT 
        '''			ft.ticket_cap_name
        '''		FROM tblRevenue rv
        '''		INNER JOIN tblFreeTicketAndCapRevenueDetail AS ftrd
        '''			ON ftrd.revenue_id = rv.revenueid
        '''		INNER JOIN tblFreeTicketAndCap AS ft
        '''			ON ft.ticket_cap_id = ftrd.ticket_cap_id
        '''		WHERE rv.movies_id = @movie_id
        '''		 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SelectFreeTicketCapMoviePrice() As String
            Get
                Return ResourceManager.GetString("SelectFreeTicketCapMoviePrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DECLARE @name_list AS NVARCHAR(MAX);
        '''DECLARE @sql AS NVARCHAR(MAX);
        '''SET @name_list = &apos;&apos;;
        '''	
        '''IF @screen_id IS NOT NULL AND @theater_id IS NOT NULL
        '''BEGIN
        '''	SELECT @name_list = @name_list + &apos;,[&apos; + ticket_cap_name + &apos;]&apos; 
        '''	FROM
        '''	(
        '''		SELECT DISTINCT 
        '''			ft.ticket_cap_name
        '''		FROM tblRevenue rv
        '''		INNER JOIN tblFreeTicketAndCapRevenueDetail AS ftrd
        '''			ON ftrd.revenue_id = rv.revenueid
        '''		INNER JOIN tblFreeTicketAndCap AS ft
        '''			ON ft.ticket_cap_id = ftrd.ticket_cap_id
        '''		WHERE rv.movies_id = @movie_id
        '''		 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SelectFreeTicketCapMovieViewer() As String
            Get
                Return ResourceManager.GetString("SelectFreeTicketCapMovieViewer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF @screen_id IS NOT NULL AND @theater_id IS NOT NULL
        '''BEGIN
        '''	SELECT
        '''		rv.revenue_date
        '''		, SUM(rv.revenue_amount_no_cap) AS revenue_report
        '''		, SUM(rv.revenue_adms_with_free_ticket) AS viewer_report
        '''		, SUM(rv.revenue_amount) AS revenue_actual
        '''		, SUM(rv.revenue_adms) AS viewer_actual
        '''		
        '''		, ISNULL(SUM(ftrd.free_ticket_quantity), 0) AS free_ticket_quantity
        '''		, ISNULL(SUM(ftrd.free_ticket_price), 0) AS free_ticket_price
        '''			
        '''		, ISNULL(SUM(ftrh.free_ticket_norm_count), 0) AS free_ticket_norm_count
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SelectReportFreeTicket() As String
            Get
                Return ResourceManager.GetString("SelectReportFreeTicket", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF @screen_id IS NOT NULL AND @theater_id IS NOT NULL
        '''BEGIN
        '''	SELECT
        '''		rv.revenue_date
        '''		, SUM(rv.revenue_amount_no_cap) AS revenue_report
        '''		, SUM(rv.revenue_adms_with_free_ticket) AS viewer_report
        '''		, SUM(rv.revenue_amount) AS revenue_actual
        '''		, SUM(rv.revenue_adms) AS viewer_actual
        '''	FROM tblRevenue rv
        '''	WHERE rv.movies_id = @movie_id
        '''		AND rv.revenue_date &gt;= @start_date
        '''		AND rv.revenue_date &lt;= @end_date
        '''		AND rv.theater_id = @theater_id
        '''		AND rv.theatersub_id = @screen_id
        '''	GROUP BY
        '''		rv.reve [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SelectRevenueMovie() As String
            Get
                Return ResourceManager.GetString("SelectRevenueMovie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DECLARE @name_list AS NVARCHAR(MAX);
        '''DECLARE @sql AS NVARCHAR(MAX);
        '''
        '''SET @name_list = &apos;&apos;;
        '''
        '''IF @screen_id IS NOT NULL AND @theater_id IS NOT NULL
        '''BEGIN
        '''	SELECT @name_list = @name_list + &apos;,[&apos; + ticket_type_name + &apos;]&apos; 
        '''	FROM
        '''	(
        '''		SELECT DISTINCT 
        '''			tt.ticket_type_name
        '''		FROM tblRevenue rv
        '''		INNER JOIN tblTheater t
        '''			ON t.theater_id = rv.theater_id
        '''		INNER JOIN tblTicketTypeRevenueDetail ttd
        '''			ON ttd.revenue_id = rv.revenueid
        '''		INNER JOIN tblTicketType tt
        '''			ON tt.ticket_type_id = ttd.ticke [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SelectTicketTypeMovie() As String
            Get
                Return ResourceManager.GetString("SelectTicketTypeMovie", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
