'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8689
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class TicketTypeRevenueHeader
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SDTCommon.TicketTypeRevenueHeader", GetType(TicketTypeRevenueHeader).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE tblTicketTypeRevenueHeader
        '''WHERE revenue_id = @revenue_id;.
        '''</summary>
        Friend Shared ReadOnly Property DeleteRevenue() As String
            Get
                Return ResourceManager.GetString("DeleteRevenue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT
        '''	rv.revenueid
        '''	, rv.revenue_adms
        '''	, rv.revenue_amount
        '''	, rv.revenue_date
        '''	, rv.revenue_Time
        '''	, rv.revenue_LastUpdate
        '''	, rv.revenue_type
        '''	, rv.theatersub_id
        '''	, rv.user_id
        '''	, rv.movie_system
        '''	, rv.movies_id
        '''	, rv.theater_id
        '''	, rv.status_id
        '''	, rv.sound_type
        '''	, rv.timehour_id
        '''	, rv.timemin_id
        '''	, rv.film_type_sound_id
        '''	, rv.revenue_amount_no_cap
        '''	, rv.revenue_adms_with_free_ticket
        '''	, rv.check_ticket
        '''	, m.movie_id
        '''	, m.movietype_id
        '''	, SUBSTRING(m.movie_nameen, 1, 15) AS ShortName
        '''	, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SelectAllIncomplete() As String
            Get
                Return ResourceManager.GetString("SelectAllIncomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''	rv.revenueid AS revenue_id
        '''	, rv.revenue_amount
        '''	, rv.revenue_amount_no_cap
        '''	, rv.revenue_adms
        '''	, rv.revenue_adms_with_free_ticket
        '''	, rv.movies_id AS movie_id
        '''
        '''	, tth.ticket_type_count
        '''	, tth.update_by
        '''	, tth.update_date
        '''	, CASE WHEN ISNULL(tth.ticket_type_count, 0) &gt; rv.revenue_adms OR (ISNULL(tth.ticket_type_count, 0) = 0 AND rv.revenue_adms &lt;&gt; 0) THEN 1 ELSE 0 END AS incomplete
        '''FROM tblRevenue AS rv
        '''LEFT JOIN tblTicketTypeRevenueHeader AS tth
        '''	ON tth.revenue_id = rv.revenueid
        '''WHER [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SelectData() As String
            Get
                Return ResourceManager.GetString("SelectData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT DISTINCT 
        '''	rv.movies_id AS movie_id
        '''FROM tblRevenue AS rv
        '''LEFT JOIN tblTicketTypeRevenueHeader AS tth
        '''	ON tth.revenue_id = rv.revenueid
        '''WHERE rv.check_ticket = 1
        '''	AND rv.theater_id = @theater_id
        '''	AND rv.revenue_date = @revenue_date
        '''	AND (ISNULL(tth.ticket_type_count, 0) &gt; rv.revenue_adms OR (ISNULL(tth.ticket_type_count, 0) = 0 AND rv.revenue_adms &lt;&gt; 0));.
        '''</summary>
        Friend Shared ReadOnly Property SelectIncompleteMovie() As String
            Get
                Return ResourceManager.GetString("SelectIncompleteMovie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE tblTicketTypeRevenueHeader
        '''SET
        '''	ticket_type_count = @ticket_type_count
        '''	, update_by = @update_by
        '''	, update_date = @cvDate
        '''WHERE revenue_id = @revenue_id;
        '''
        '''IF @@ROWCOUNT = 0
        '''BEGIN
        '''	INSERT INTO tblTicketTypeRevenueHeader
        '''(
        ''' revenue_id
        ''' , ticket_type_count
        ''' , update_by
        ''' , update_date
        ''')
        '''VALUES
        '''(
        ''' @revenue_id
        ''' , @ticket_type_count
        ''' , @update_by
        ''' , @cvDate
        ''');
        '''END.
        '''</summary>
        Friend Shared ReadOnly Property UpdateInsert() As String
            Get
                Return ResourceManager.GetString("UpdateInsert", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
